nei<-readRDS("../data/summarySCC_PM25.rds")
scc<-readRDS("../data/Source_Classification_Code.rds")
neiBalt<-subset(nei,fips == "24510",select=c(Emissions,type,year))
neiBalt$year<-factor(neiBalt$year)
ppmByYearBaltimore<-aggregate(neiBalt$Emissions,by=list(neiBalt$year,neiBalt$type),sum)
png(filename = "plot3.png",width=480,height=480,type="windows",pointsize = 12)
library(ggplot2)
p <- ggplot(neiBalt, aes(year,Emissions)) + geom_bar(stat="identity")
p + facet_grid(. ~ type)
dev.off()
